HOST: "localhost"
PORT: 4000
DATABASE_USER: "postgres"
DATABASE_PASS: "postgres"
DATABASE_DB: "shoutouts_dev"
DATABASE_HOST: "localhost"
SECRET_KEY_BASE: "CDefhp5OjWSBOuBgbcYlgLMLIY23jtVcZ7YkljZpxBlvEDsEI8BBdJiqWqNzOfm0"
GITHUB_TOKEN: ""
GITHUB_APP_ID: ""
GITHUB_CLIENT_ID: ""
GITHUB_CLIENT_SECRET: ""
SENTRY_DSN: ""
DASHBOARD_USER: "yeray"
DASHBOARD_PASS: "dashboard"
