use Mix.Config

config :shoutouts, :env, :prod

config :shoutouts, Shoutouts.Scheduler,
  jobs: [
    # 01:39 on every 3rd day-of-month
    {"39 1 */3 * *", {Shoutouts.Projects, :refresh_projects, [7]}},
    # 7:42 on Sunday
    {"42 7 * * 0", {ShoutoutsWeb.Email.Emails, :send_shoutouts_digest, []}}
  ]

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :shoutouts_web, ShoutoutsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  transport_options: [
    socket_opts: [:inet6]
  ],
  # boot cowboy on start
  server: true,
  # configure app to serve static assets
  root: ".",
  # cache bust on upgrades
  version: Application.spec(:shoutouts_web, :vsn)

config :shoutouts_web, ShoutoutsWeb.Email.Mailer,
  adapter: Bamboo.SendGridAdapter,
  hackney_opts: [
    recv_timeout: :timer.minutes(1)
  ]

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :shoutouts_web, ShoutoutsWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :shoutouts_web, ShoutoutsWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Do not print debug messages in production
config :logger, level: :info

# The only difference with dev is `wss`
config :plug_content_security_policy,
  nonces_for: [],
  report_only: false,
  directives: %{
    default_src: ~w('self'),
    img_src: ~w('self' data: https://*.githubusercontent.com),
    style_src: ~w('self' 'unsafe-inline'),
    script_src: ~w('self' https://plausible.io),
    connect_src: ~w('self' wss: https://plausible.io)
  }

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"

config :appsignal, :config, active: true
